# Generated by Django 6.0.3 on 2026-04-07 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyplan',
            options={'verbose_name': 'Дисциплина плана', 'verbose_name_plural': 'Учебный план (список)'},
        ),
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='course_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кредиты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='users.group'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='users.subject'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='credits',
        ),
    ]
