# Generated by Django 6.0.3 on 2026-04-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studyplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.subject', verbose_name='Преподаваемые предметы'),
        ),
    ]
