# Generated by Django 6.0.3 on 2026-04-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_subject_user_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1 семестр'), (2, '2 семестр')], verbose_name='Семестр')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.group')),
            ],
            options={
                'verbose_name': 'Учебный план на семестр',
                'verbose_name_plural': 'Учебные планы',
                'unique_together': {('group', 'course_number', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.semesterplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предмет плана',
                'verbose_name_plural': 'Предметы плана',
            },
        ),
    ]
