# Generated by Django 6.0.3 on 2026-04-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_lesson_course'),
        ('users', '0004_semesterplan_semestersubject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
