# Generated by Django 6.0.3 on 2026-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_moduleplan_modulesubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleplan',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Модуль'), (2, '2 Модуль')], verbose_name='Модуль'),
        ),
    ]
