# Generated by Django 6.0.3 on 2026-04-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_lesson_course'),
        ('users', '0007_alter_moduleplan_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestersubject',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='semestersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='semestersubject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='SemesterPlan',
        ),
        migrations.DeleteModel(
            name='SemesterSubject',
        ),
    ]
