# Generated by Django 6.0.3 on 2026-04-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_lesson_course'),
        ('users', '0009_alter_moduleplan_module_semesterplan_semestersubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesubject',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='modulesubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='modulesubject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ModulePlan',
        ),
        migrations.DeleteModel(
            name='ModuleSubject',
        ),
    ]
