# Generated by Django 6.0.3 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_modulesubject_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.AddField(
            model_name='group',
            name='start_year',
            field=models.PositiveIntegerField(default=2026, verbose_name='Год поступления'),
        ),
    ]
