# Generated by Django 6.0.3 on 2026-04-07 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.studyplan', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schedule.campus'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room', verbose_name='Кабинет'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('room', 'date', 'lesson_number')},
        ),
    ]
