# Generated by Django 6.0.3 on 2026-04-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_lesson_course'),
        ('users', '0005_delete_studyplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.semestersubject', verbose_name='Курс'),
        ),
    ]
