# Generated by Django 6.0.3 on 2026-04-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_lesson_course'),
        ('users', '0009_alter_moduleplan_module_semesterplan_semestersubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.semestersubject', verbose_name='Курс'),
        ),
    ]
