# Generated by Django 6.0.3 on 2026-04-09 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_lesson_course'),
        ('users', '0011_remove_group_course_group_start_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('lesson_number', models.IntegerField(choices=[(1, '08:00 – 09:20'), (2, '09:30 – 10:50'), (3, '11:00 – 12:20'), (4, '12:30 – 13:50')], verbose_name='Пара №')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room')),
                ('semester_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.semestersubject')),
            ],
            options={
                'verbose_name': 'Расписание (шаблон)',
                'verbose_name_plural': 'Расписание (шаблоны)',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина отсутствия')),
                ('semester_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.semestersubject')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'semester_subject', 'date')},
            },
        ),
    ]
