# Generated by Django 6.0.3 on 2026-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_scheduleslot_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная')], default=1, max_length=20, verbose_name='Тип занятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная')], default='practice', max_length=20, verbose_name='Тип занятия'),
        ),
    ]
