# Generated by Django 6.0.3 on 2026-04-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_lesson_lesson_type_scheduleslot_lesson_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
