# Generated by Django 5.2.10 on 2026-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_question_order_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
